spring.application.name=nodes-jdbc-demo

spring.datasource.driver-class-name=org.neo4j.jdbc.Neo4jDriver
spring.datasource.url=jdbc:neo4j://localhost:7687
#spring.datasource.url=jdbc:neo4j:http://localhost:7474
spring.datasource.username=neo4j
spring.datasource.password=secret12345!

management.endpoints.web.exposure.include=prometheus,health,info,metrics,trace
management.endpoint.prometheus.access=unrestricted
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces

#logging.level.org.neo4j.jdbc.network=DEBUG
